apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  # namespace: orders
spec:
  replicas: 1  # Single pod (no scaling)
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: web
        image: weshigbee/orders-sluggish:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  # namespace: orders
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 3000 
      targetPort: 3000
      nodePort: 30080 
  type: NodePort
  # type: LoadBalancer  # Expose externally (if running on cloud)
